// const data = [
//     {id: 'kim', message: 'hi my name is kim'},
//     {id: 'kim2', message: 'hi my name is kim'},
//     {id: 'kim3', message: 'hi my name is kim'},
//     {id: 'kim4', message: 'hi my name is kim'},
//     {id: 'kim5', message: 'hi my name is kim'},
//     {id: 'kim6', message: 'hi my name is kim'},
//     {id: 'kim7', message: 'hi my name is kim'},
//     {id: 'kim8', message: 'hi my name is kim'},
//     {id: 'kim9', message: 'hi my name is kim'},
//     {id: 'kim02', message: 'hi my name is kim'},
//     {id: 'kim134', message: 'hi my name is kim'},
//     {id: 'kim243', message: 'hi my name is kim'},
//     {id: 'kim3557', message: 'hi my name is kim'},
//     {id: 'kim4556', message: 'hi my name is kim'},
//     {id: 'kim7687', message: 'hi my name is kim'},
//     {id: 'kim34', message: 'hi my name is kim'},
//     {id: 'kim23f', message: 'hi my name is kim'},
//     {id: 'kim23d', message: 'hi my name is kim'},
//     {id: 'kim23feew', message: 'hi my name is kim'},
//     {id: 'kim', message: 'hi my name is kim'},
//     {id: 'kim2', message: 'hi my name is kim'},
//     {id: 'kim3', message: 'hi my name is kim'},
//     {id: 'kim4', message: 'hi my name is kim'},
//     {id: 'kim5', message: 'hi my name is kim'},
//     {id: 'kim6', message: 'hi my name is kim'},
//     {id: 'kim7', message: 'hi my name is kim'},
//     {id: 'kim8', message: 'hi my name is kim'},
//     {id: 'kim9', message: 'hi my name is kim'},
//     {id: 'kim02', message: 'hi my name is kim'},
//     {id: 'kim134', message: 'hi my name is kim'},
//     {id: 'kim243', message: 'hi my name is kim'},
//     {id: 'kim3557', message: 'hi my name is kim'},
//     {id: 'kim4556', message: 'hi my name is kim'},
//     {id: 'kim7687', message: 'hi my name is kim'},
//     {id: 'kim34', message: 'hi my name is kim'},
//     {id: 'kim23f', message: 'hi my name is kim'},
//     {id: 'kim23d', message: 'hi my name is kim'},
//     {id: 'kim23feew', message: 'hi my name is kim'},
//     {id: 'kim', message: 'hi my name is kim'},
//     {id: 'kim2', message: 'hi my name is kim'},
//     {id: 'kim3', message: 'hi my name is kim'},
//     {id: 'kim4', message: 'hi my name is kim'},
//     {id: 'kim5', message: 'hi my name is kim'},
//     {id: 'kim6', message: 'hi my name is kim'},
//     {id: 'kim7', message: 'hi my name is kim'},
//     {id: 'kim8', message: 'hi my name is kim'},
//     {id: 'kim9', message: 'hi my name is kim'},
//     {id: 'kim02', message: 'hi my name is kim'},
//     {id: 'kim134', message: 'hi my name is kim'},
//     {id: 'kim243', message: 'hi my name is kim'},
//     {id: 'kim3557', message: 'hi my name is kim'},
//     {id: 'kim4556', message: 'hi my name is kim'},
//     {id: 'kim7687', message: 'hi my name is kim'},
//     {id: 'kim34', message: 'hi my name is kim'},
//     {id: 'kim23f', message: 'hi my name is kim'},
//     {id: 'kim23d', message: 'hi my name is kim'},
//     {id: 'kim23feew', message: 'hi my name is kim'},
//     {id: 'kim', message: 'hi my name is kim'},
//     {id: 'kim2', message: 'hi my name is kim'},
//     {id: 'kim3', message: 'hi my name is kim'},
//     {id: 'kim4', message: 'hi my name is kim'},
//     {id: 'kim5', message: 'hi my name is kim'},
//     {id: 'kim6', message: 'hi my name is kim'},
//     {id: 'kim7', message: 'hi my name is kim'},
//     {id: 'kim8', message: 'hi my name is kim'},
//     {id: 'kim9', message: 'hi my name is kim'},
//     {id: 'kim02', message: 'hi my name is kim'},
//     {id: 'kim134', message: 'hi my name is kim'},
//     {id: 'kim243', message: 'hi my name is kim'},
//     {id: 'kim3557', message: 'hi my name is kim'},
//     {id: 'kim4556', message: 'hi my name is kim'},
//     {id: 'kim7687', message: 'hi my name is kim'},
//     {id: 'kim34', message: 'hi my name is kim'},
//     {id: 'kim23f', message: 'hi my name is kim'},
//     {id: 'kim23d', message: 'hi my name is kim'},
//     {id: 'kim23feew', message: 'hi my name is kim'},
//     {id: 'kim', message: 'hi my name is kim'},
//     {id: 'kim2', message: 'hi my name is kim'},
//     {id: 'kim3', message: 'hi my name is kim'},
//     {id: 'kim4', message: 'hi my name is kim'},
//     {id: 'kim5', message: 'hi my name is kim'},
//     {id: 'kim6', message: 'hi my name is kim'},
//     {id: 'kim7', message: 'hi my name is kim'},
//     {id: 'kim8', message: 'hi my name is kim'},
//     {id: 'kim9', message: 'hi my name is kim'},
//     {id: 'kim02', message: 'hi my name is kim'},
//     {id: 'kim134', message: 'hi my name is kim'},
//     {id: 'kim243', message: 'hi my name is kim'},
//     {id: 'kim3557', message: 'hi my name is kim'},
//     {id: 'kim4556', message: 'hi my name is kim'},
//     {id: 'kim7687', message: 'hi my name is kim'},
//     {id: 'kim34', message: 'hi my name is kim'},
//     {id: 'kim23f', message: 'hi my name is kim'},
//     {id: 'kim23d', message: 'hi my name is kim'},
//     {id: 'kim23feew', message: 'hi my name is kim'},
//     {id: 'kim', message: 'hi my name is kim'},
//     {id: 'kim2', message: 'hi my name is kim'},
//     {id: 'kim3', message: 'hi my name is kim'},
//     {id: 'kim4', message: 'hi my name is kim'},
//     {id: 'kim5', message: 'hi my name is kim'},
//     {id: 'kim6', message: 'hi my name is kim'},
//     {id: 'kim7', message: 'hi my name is kim'},
//     {id: 'kim8', message: 'hi my name is kim'},
//     {id: 'kim9', message: 'hi my name is kim'},
//     {id: 'kim02', message: 'hi my name is kim'},
//     {id: 'kim134', message: 'hi my name is kim'},
//     {id: 'kim243', message: 'hi my name is kim'},
//     {id: 'kim3557', message: 'hi my name is kim'},
//     {id: 'kim4556', message: 'hi my name is kim'},
//     {id: 'kim7687', message: 'hi my name is kim'},
//     {id: 'kim34', message: 'hi my name is kim'},
//     {id: 'kim23f', message: 'hi my name is kim'},
//     {id: 'kim23d', message: 'hi my name is kim'},
//     {id: 'kim23feew', message: 'hi my name is kim'},
//
// ]
const data= []
const datafetch = () => {
    return new Promise ((resolve, reject)=>{
        setTimeout(()=>{
            resolve(data);
        })
    })
}

const dataadd = (value) => {
    data.push(value);
    return new Promise ((resolve, reject)=>{
        setTimeout(()=>{
            resolve(data);
        })
    })
}

export {datafetch, dataadd};